### ISSUE TITLE
Curios

### ISSUE THREAD

**Issue by Cartrigger** [BluSpring/Kilt#35]
### Version information

The Aether - 1.20.1 - 1.5.0-neoforge

### Reproduction Steps

Put the mod in the mods folder
Start the game
profit

### Java version

21

### Crash Report file

https://mclo.gs/y1boItq

### Additional information

Seems to be a issue with curios and other JIJ mods

**Comment by BluSpring** [comment]
It is not, but fixing this crash might involve some ASM trickery, which I was already intending on doing anyway to make this class work.

**Comment by Cartrigger** [comment]
I meant the crash is from probably other JIJ mods included, not JIJ itself

**Comment by BluSpring** [comment]
There exists a new crash with the Aether that I legitimately cannot fix due to FabricMC/Mixin#134 having not been fixed.
This is gonna be a fun experience.

**Comment by Cartrigger** [comment]
time to do the waiting game until merged?

**Comment by Adidiii** [comment]
Would FabricMC/Mixin/pull/154 fix this? It's still pending, and only time will tell when it'll get merged, but I see it as a simple fix

**Comment by kir-kir** [comment]
Yes.

**Comment by Adidiii** [comment]
Then I guess we're just going to have to play the waiting game

**Comment by BluSpring** [comment]
Fixed in d6eef67e91d85e6c4ed7942d704d4e08ffdf92c5.

**Comment by Cartrigger** [comment]
https://mclo.gs/zg4A2Ps its not fixed

**Comment by Cartrigger** [comment]
ill switch this over to curios only just because aether is fabric now

**Comment by Adidiii** [comment]
I wouldn't close this just because you found a solution, the problem still exists

**Comment by Cartrigger** [comment]
> I wouldn't close this just because you found a solution, the problem still exists

Curios opens.
On top of that, the Aether is N/A as a Fabric release is out.
